server.servlet.encoding.force-response: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

